/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jportaudio_PaWasapiStreamInfo */

#ifndef _Included_com_jportaudio_PaWasapiStreamInfo
#define _Included_com_jportaudio_PaWasapiStreamInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jportaudio_PaWasapiStreamInfo
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jportaudio_PaWasapiStreamInfo_getData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
