/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jportaudio;

import org.junit.Test;

import static org.junit.Assert.*;

public class PortAudioTest {
    @Test
    public void testInitPortAudio() {
        try {
            PortAudio.init();

            System.out.println(PortAudio.getVersionText());
            System.out.println(PortAudio.getVersionControlRevision());

            PortAudio.terminate();
        } catch (RuntimeException e) {
            System.out.println(e);
            fail();
        }
    }

    @Test public void testHostApi() {
        try {
            PortAudio.init();

            for (int i = 0; i < PortAudio.getHostApiCount(); i++) {
                HostApi ha = PortAudio.getHostApi(i);
                System.out.println(ha.toString());
                System.out.println("defaultInput=" + ha.getDefaultInputDevice() +
                        " defaultOutput=" + ha.getDefaultOutputDevice());
            }

            System.out.println("Default Host Api:");
            System.out.println(PortAudio.getDefaultHostApi().toString());

            PortAudio.terminate();
        } catch (RuntimeException e) {
            System.out.println(e);
            fail();
        }
    }
}
